//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIERUNKI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KIERUNKI()
        {
            this.STUDENCI = new HashSet<STUDENCI>();
        }
    
        public int ID_KIERUNKU { get; set; }
        public string NAZWA_KIERUNKU { get; set; }
        public string TYP_STUDIOW { get; set; }
        public decimal CZAS_TRWANIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENCI> STUDENCI { get; set; }
    }
}
