//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracownicyPracownicze
    {
        public string NazwaBiura { get; set; }
        public string Adres { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
    }
}
