//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRZEDMIOTY
    {
        public int ID_PRZEDMIOTU { get; set; }
        public string NAZWA { get; set; }
        public string OPIS { get; set; }
        public decimal ILOSC { get; set; }
        public int ID_SALI { get; set; }
    
        public virtual SALE SALE { get; set; }
    }
}
