//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZERWACJE
    {
        public int ID_REZERWACJI { get; set; }
        public System.DateTime REZERWACJA_OD { get; set; }
        public Nullable<System.DateTime> REZERWACJA_DO { get; set; }
        public float CENA { get; set; }
        public int NR_ALBUMU { get; set; }
        public int ID_SALI { get; set; }
        public int ID_PRACOWNIKA { get; set; }
    
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual SALE SALE { get; set; }
        public virtual STUDENCI STUDENCI { get; set; }
    }
}
